export interface Coin {
  symbol: string;
  name: string;
  price: number;
  change24h: number;
  marketCap: string;
  volume: string;
  history: number[];    // real 24h price series (hourly sparkline), refreshed each
                        // poll; graphs append the live price as the right-edge tip
  high24h?: number;     // raw USD from CoinGecko, undefined until first UPDATE_PRICES
  low24h?: number;
}

export interface Holding {
  symbol: string;
  units: number;
  avgCost: number;
}

export interface Trade {
  id: string;
  symbol: string;
  side: 'buy' | 'sell';
  amount: number;
  units: number;
  price: number;
  timestamp: number;
  xpEarned: number;
  slippage: number;
  // 'reward' = a cash-injection event (e.g. daily-reward bonus), recorded with
  // symbol 'USD' (the CASH_EVENT_SYMBOL sentinel), units 0, amount = bonus. It
  // is not a coin trade; ledger replay treats symbol 'USD' as a pure cash delta.
  // 'rebalance' = a coin buy/sell generated by the Rebalance action (vs a manual
  // trade), so the history can mark it "(rebalanced)". Persists for the offline
  // portfolio (local store); cloud rows have no `kind` column.
  // Optional/back-compat: undefined on coin trades and on rows reloaded from the
  // cloud (the Trade model has no `kind` column — the symbol carries the mark).
  kind?: 'trade' | 'reward' | 'rebalance';
  // Realized P&L on a sell, in dollars (proceeds − cost basis at avgCost). Set
  // when the sell executes; undefined on buys/older rows.
  realizedPnl?: number;
}

export interface Tournament {
  id: string;
  name: string;
  type: 'daily' | 'featured' | 'replay' | '1v1';
  status: 'live' | 'open' | 'finished';
  prizePool: string;
  players: number;
  userRank: number;
  endsAt: number;
  stake: string;
}

export interface Competition {
  id: string;
  name: string;
  type: 'daily' | 'featured' | 'replay' | '1v1';
  status: 'open' | 'live' | 'finished';
  prizePool: string;
  maxPlayers: number;
  stake: string;
  startAt: number;
  endAt: number;
  entryCount: number;
  numberOfPrizes: number;   // count of paid positions
  prizes: number[];         // dollar amount per rank (index 0 = #1)
  prizeXp: number;          // winner's XP award when cash prizes are off (podium splits it)
  inviteCode?: string;      // 1v1 duels only — shareable join code
  challengerHandle?: string; // 1v1 duels only — who created the duel
  // When true, no new entries are accepted once the contest has started
  // (now >= startAt). Default false = players can still join live.
  lockAfterStart?: boolean;
  // Fraction of elapsed time (0..1) after which joining closes — e.g. 0.9 means
  // "joinable until only 10% of the duration remains". Undefined = joinable until
  // the contest ends. See isJoinLocked() in competitionService.
  joinCutoffPct?: number;
  // True for real-money cash-prize contests. Payments-off builds filter these
  // out (query + client guard) so they never appear there. Legacy/XP contests
  // are false/undefined and show on every build.
  cashPrize?: boolean;
}

export interface CompetitionEntry {
  id: string;
  competitionId: string;
  handle: string;
  bankroll: number;
  pnlPct: number;
  rank: number;
  joinedAt: number;
  isActive: boolean;
}

export interface PendingOrder {
  id: string;
  symbol: string;
  side: 'buy' | 'sell';
  amount: number;
  limitPrice: number;
  createdAt: number;
}

export interface CoachNudge {
  id: string;
  message: string;
  severity: 'info' | 'warn' | 'tip';
  createdAt: number;
}

export interface PriceAlert {
  id: string;
  symbol: string;
  targetPrice: number;
  direction: 'above' | 'below';
  createdAt: number;
  triggeredAt?: number;
}

// A user the current device has blocked. Identified by the reported trader's
// PublicProfile owner (Cognito sub) when available; for leaderboard entries
// that don't expose an owner, `owner` falls back to the handle. `handle` is
// kept for display on the Blocked-users screen. Blocked users are filtered out
// of every feed (top traders, leaderboards, copy-trade) instantly.
export interface BlockedUser {
  owner: string;
  handle: string;
}

// A trading portfolio — either the main offline portfolio (id: 'main') or a
// per-contest portfolio (id: competitionId). Each is independent: separate
// $100K starting cash, separate holdings, separate trades.
export interface PortfolioSlice {
  cash: number;
  holdings: Holding[];
  trades: Trade[];
}

// A joined replay contest's immutable config, kept in state so the deterministic
// price can be computed locally each tick. `prices` is the real 1-minute close
// series; the current price is prices[floor((now-startAt)/intervalMs)].
export interface ReplayMeta {
  coin: string;
  histStartIso: string;   // ISO date of prices[0] — drives the "(Month D, YYYY)" label
  startAt: number;        // ms epoch the contest clock starts (real time)
  endAt: number;          // startAt + (prices.length × intervalMs)
  intervalMs: number;     // REAL ms per step (contests: 60000 = real-time 1:1)
  prices: number[];       // close series, oldest → newest
  // HISTORICAL ms each step represents. Defaults to intervalMs (contests are
  // 1:1). Solo replays accelerate — e.g. intervalMs 3000 (3s/step) with
  // histStepMs 86400000 (one day/step) fast-forwards a daily era in minutes,
  // while the date label still advances a full day per step.
  histStepMs?: number;
  // True for a locally-created solo replay (no cloud entry, no leaderboard).
  solo?: boolean;
  // Display name (solo replays aren't in the server contest list, so they carry
  // their own title for the pill + header eyebrow).
  title?: string;
}

// Lightweight replay-contest row for the Compete browse list (no heavy pricesJson).
export interface ReplayContestSummary {
  id: string;
  eventId: string;
  eventTitle: string;
  coin: string;
  weekIndex: number;
  histStartIso: string;
  startAt: number;
  endAt: number;
  status: 'open' | 'live' | 'finished';
  intervalMs: number;
  maxPlayers: number;
  prizeXp: number;
  lockAfterStart: boolean;
  entryCount: number;
}

export interface AppState {
  user: {
    handle: string;
    xp: number;
    league: string;
    division: number;
    streak: number;
    avatarColor: string;
    avatarUri?: string;   // resolvable URL (signed if from S3, local file:// if just picked)
    avatarKey?: string;   // stable S3 key for cloud persistence (e.g. "profile.jpg")
    createdAt?: number;   // ms epoch — when this UserProfile row was created in DynamoDB
    // Whether the user appears on the public global leaderboard. Defaults to
    // true (opt-out). Toggled in Settings; persisted to UserProfile.
    leaderboardVisible?: boolean;
  };
  bankroll: number;
  cash: number;
  holdings: Holding[];
  trades: Trade[];
  coins: Coin[];
  // Active portfolio selector. 'main' = offline personal portfolio, otherwise
  // it's the competitionId of a joined contest. Whichever is active drives
  // state.cash / state.holdings / state.trades. Inactive portfolios are
  // stashed in `portfolios` until switched back to.
  activePortfolioId: string;
  portfolios: Record<string, PortfolioSlice>;
  // Replay contests the user has joined. The portfolio slice lives in
  // `portfolios[replayContestId]` (so the selector pill + equity capture work);
  // these hold the replay-specific config + deterministic current price.
  joinedReplayIds: string[];
  replayMeta: Record<string, ReplayMeta>;
  replayPrices: Record<string, number>;   // authoritative minute-close price per joined replay
  replayContests: ReplayContestSummary[]; // browsable list for the Compete → Replay tab
  activeTournament: Tournament | null;
  competitions: Competition[];
  // Ended contests, moved server-side into the FinishedCompetition table. Shown
  // under the "Past" tab on Compete.
  finishedCompetitions: Competition[];
  joinedTournamentIds: string[];
  leaderboard: Record<string, CompetitionEntry[]>;
  // The user's own contest-win count, computed locally so it shows even when
  // opted out of the global leaderboard (where the count otherwise comes from).
  myContestWins: number;
  pendingOrders: PendingOrder[];
  watchlist: string[];
  riskScore: number;
  // Sell-stop per coin: % below entry (avgCost) at which the WHOLE position
  // auto-sells. Keyed by symbol, one per coin. Drives risk score + coach nudges.
  stopLosses: Record<string, number>;
  // Buy-stop per coin: auto-buy `amount` dollars when price falls to `price`.
  // Keyed by symbol, one per coin. The buy-side counterpart to stopLosses.
  buyStops: Record<string, { price: number; amount: number }>;
  priceAlerts: PriceAlert[];
  triggeredAlerts: PriceAlert[];
  coachNudges: CoachNudge[];
  dismissedNudgeIds: string[];
  hasOnboarded: boolean;
  onboardingChecked: boolean;   // true once the persisted onboarding flag has been read at launch
  tradeSymbol: string;
  // Daily-reward claim tracking. UTC day-key ("YYYY-MM-DD") of the last claim,
  // or null if never claimed. Drives the streak (see user.streak) and the
  // "claim available / come back tomorrow" state. Persisted to AsyncStorage
  // ('gamification.v1'); cloud sync added later via UserProfile.gamificationJson.
  lastClaimDay: string | null;
  // Unlocked achievements: achievement id → unlockedAt (ms epoch). Persisted in
  // 'gamification.v1'. The watcher evaluates the engine and records new unlocks.
  achievements: Record<string, number>;
  // Crypto Academy: ids of completed lessons (see src/data/academy.ts). Persisted
  // in the gamification blob; drives Learn progress + the 'graduate' achievement.
  academyCompleted: string[];
  // Price-prediction mini-game lifetime stats (Phase 5). Persisted in
  // 'gamification.v1'. predictionWins feeds the "Predictor" achievement.
  predictionWins: number;
  predictionLosses: number;
  // Current consecutive-correct prediction streak. Drives the +500/step streak
  // bonus (see PREDICTION_STREAK_XP). Resets to 0 on a loss. Persisted in the
  // gamification.v1 blob.
  predictionStreak: number;
  // Contest ids whose XP prize the user has already claimed, so a contest's XP
  // is never awarded twice. Persisted in the gamification.v1 blob.
  claimedContestIds: string[];
  // Count of duels this user has created — drives the incrementing "Duel #N"
  // name. Persisted in the gamification.v1 blob.
  duelsCreated: number;
  // Daily Quests — today's progress + claims. `dayKey` is the UTC day these
  // belong to; on rollover the baseline re-snapshots and claims clear (see
  // ROLL_QUEST_DAY). `baseline` holds counters captured at day-start for metrics
  // that lack per-event timestamps. Persisted in the gamification.v1 blob.
  quests: {
    dayKey: string | null;
    baseline: { predictionsTotal: number; lessonsTotal: number; watchlistCount: number };
    claimedIds: string[];
    chestClaimed: boolean;
  };
  // Season Pass — `id` is the current 28-day window; `baselineXp` is lifetime XP
  // at season start (seasonXp = user.xp − baselineXp); `claimedTiers` are the
  // tier numbers already collected this season. Reset on a new season (cosmetics
  // are kept). Persisted in the gamification.v1 blob.
  season: {
    id: number | null;
    baselineXp: number;
    claimedTiers: number[];
  };
  // Unlocked + equipped cosmetics (titles, avatar frames). Persist across seasons.
  cosmetics: {
    titles: string[];
    frames: string[];
    equippedTitle: string | null;
    equippedFrame: string | null;
  };
  // Lane-A (virtual) contest entry passes. `balance` is spent to join a virtual
  // contest; topped up by a free weekly grant and by watching rewarded ads (never
  // bought — no IAP). `lastWeeklyGrantKey` is the weekKey() of the last free grant
  // so it lands once per week. Cash (Lane B) contests are NEVER gated on passes.
  // Persisted in the gamification.v1 blob.
  passes: {
    balance: number;
    lastWeeklyGrantKey: string | null;
  };
  // Premium subscriber entitlement. Drives the larger weekly pass grant (and, in
  // future, no-ads + the $1M balance perk). Source of truth will be the store /
  // RevenueCat entitlement once IAP ships (future scope) — never trust a local
  // value for anything that costs real money. Defaults false; no setter yet.
  isSubscriber: boolean;
  // The one in-flight price prediction (only one at a time). Persisted in the
  // gamification.v1 blob so it survives navigating away / backgrounding, and
  // surfaced on the Compete page. null when no round is pending.
  activePrediction?: {
    symbol: string;
    direction: 'up' | 'down';
    lockedPrice: number;
    startedAt: number;
    expiresAt: number;   // ms epoch — when the 60s round resolves
  } | null;
  // Users this device has blocked. Persisted to AsyncStorage ('blocked.v1')
  // and preserved across sign-out (per-device, not per-account). Every
  // user-content feed filters these out. See BlockedUser.
  blockedUsers: BlockedUser[];
  // External market context, refreshed alongside fetchPrices.
  globalStats?: { totalMarketCap: number; change24h: number };
  fearGreed?:   { value: number; label: string };
  // Bumped to Date.now() by RESET_DEMO. An effect watches it to wipe + re-seed
  // the equity graph at the reset moment. Ephemeral (not persisted), so it never
  // re-fires on app reload.
  resetAt?: number;
}
